export const getFlagUrl = (countryName) => {
  const mapping = {
    'México': 'mx',
    'Sudáfrica': 'za',
    'Corea del Sur': 'kr',
    'República de Corea': 'kr',
    'República Checa': 'cz',
    'Chequia': 'cz',
    'Canadá': 'ca',
    'Bosnia y Herzegovina': 'ba',
    'Estados Unidos': 'us',
    'Paraguay': 'py',
    'Catar': 'qa',
    'Suiza': 'ch',
    'Brasil': 'br',
    'Marruecos': 'ma',
    'Haití': 'ht',
    'Escocia': 'gb-sct',
    'Australia': 'au',
    'Turquía': 'tr',
    'Alemania': 'de',
    'Curazao': 'cw',
    'Curaçao': 'cw',
    'Países Bajos': 'nl',
    'Japón': 'jp',
    'Costa de Marfil': 'ci',
    'Ecuador': 'ec',
    'Suecia': 'se',
    'Túnez': 'tn',
    'España': 'es',
    'Cabo Verde': 'cv',
    'Bélgica': 'be',
    'Egipto': 'eg',
    'Arabia Saudita': 'sa',
    'Arabia Saudí': 'sa',
    'Uruguay': 'uy',
    'Irán': 'ir',
    'Nueva Zelanda': 'nz',
    'Francia': 'fr',
    'Senegal': 'sn',
    'Irak': 'iq',
    'Noruega': 'no',
    'Argentina': 'ar',
    'Argelia': 'dz',
    'Austria': 'at',
    'Jordania': 'jo',
    'Costa Rica': 'cr',
    'Camerún': 'cm',
    'Inglaterra': 'gb',
    'Italia': 'it',
    'Portugal': 'pt',
    'Colombia': 'co',
    'RD Congo': 'cd',
    'Uzbekistán': 'uz',
    'Croacia': 'hr',
    'Ghana': 'gh',
    'Panamá': 'pa'
  };
  const code = mapping[countryName];
  return code ? `https://flagcdn.com/w80/${code}.png` : `https://placehold.co/80x50/1f2937/ffffff?text=${countryName.substring(0, 3).toUpperCase()}`;
};
